### ISSUE TITLE
GraphQL Error Argument "filter" has invalid value 

### ISSUE THREAD

**Issue by Anaizing** [haysclark/gatsby-starter-casper#14]
![image](https://user-images.githubusercontent.com/29471810/37126551-a30eb102-22c5-11e8-8133-c7a0c5bd8dee.png)

Having a bit of trouble with graphQL here, this is happening as soon as I try to build new `sample-posts`. This is the second time, I have started the project from scratch and the file its pointing me to has not been altered.

Any ideas would be greatly appreciated.
Im running gatsby 1.1.45
node v8.9.1
on Windows 10

![image](https://user-images.githubusercontent.com/29471810/37126478-54429da4-22c5-11e8-83f6-50e43dc20e40.png)

**Comment by haysclark** [comment]
@Anaizing Thank you for adding the OS and NodeJS information.  Unfortunately, I don't have much experience running NodeJS on Windows.  When using Windows I typically run VirtualBox for server work, because most servers I work on professionally are Linux based.

If the starter 'works' before you start editing then try deleting your post which broke the site and restart the _develop_ npm script.  If things work again, I would try copying and pasting an existing post folder.  Update the folder name to be unique but similar to an existing date, making sure that there are no upper-case or spaces in the folder name.  Then just update the index.md inside the folder by one day.  Lastly, make sure you are using a good text editor like Atom, Sublime, etc.  It's possible that your text editor is adding funny characters.  Then, when you re-run _develop_, the duplicated post should show up.  If it did not, then run a DIFF against the original post.

Hopefully, that helps!

**Comment by Anaizing** [comment]
Hi Thank you @haysclark. I upgraded gatsby to ^1.9.130. 
Restarted the project from scratch.
Tried breaking the build by deleting posts and editing them. 
SEEMS THE UPGRADE WORKED Thank you

That is until I added a new json file to `sample-authors` but ill open a new issue if need be

**Comment by haysclark** [comment]
Awesome! VS Code and Yarn are both great. 👍

I feel like we sorted out the _404_ problem, thus I'm closing the issue.  My hope is that the remaining parsing challenges will get sorted out in Issue #15.
